name: Docker

on:
  push:
    branch:
      - master

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  # bump
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Calculate needed properties for ENV
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        
          # Calculate short SHA
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)

          # Strip git ref prefix from version
          BRANCH=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          echo "TAG=$IMAGE_ID:$BRANCH-$SHORT_SHA-$(date +%s)" >> $GITHUB_ENV
          
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Github Registr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          push: true
          tags: ${{ env.TAG }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
